DROP TABLE IF EXISTS pid_prescription;
CREATE TABLE pid_prescription(
   Pid        INTEGER  references patient(id)
  ,Issue_date DATETIME
  ,Content    VARCHAR(231) 
  ,Status     BOOLEAN
  ,primary key(Pid,Issue_date)
);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (946,'2021-03-05','ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (571,'2021-12-20','Bayberry',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (454,'2021-09-13','Simvastatin',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (724,'2021-04-08','Dextromethorphan HBr, Guaifenesin, Phenylephrine HCl',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (546,'2021-12-16','Feather Mix',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (734,'2021-11-28','Quack Grass',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (951,'2021-07-02','DEXTROMETHORPHAN HYDROBROMIDE',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (513,'2021-05-24','Magnesium Sulfate',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (959,'2022-01-07','Desoximetasone',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (145,'2021-11-23','Atorvastatin Calcium',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (722,'2021-05-21','Levetiracetam',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (674,'2021-02-19','Ciprofloxacin',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (795,'2021-06-19','TRICHOPHYTON MENTAGROPHYTES',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (180,'2021-05-10','Bupropion Hydrochloride',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (61,'2021-10-12','Johnson Grass',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (107,'2021-03-14','ONDANSETRON',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (511,'2021-02-25','Pyrithione Zinc',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (922,'2021-04-05','Triamterene and Hydrochlorothiazide',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (896,'2021-10-25','DROSERA, ARNICA MONTANA, BRYONIA, CETRARIA ISLANDICA, BELLADONNA, COCCUS CACTI, STANNUM METALLICUM, CHAMOMILLA, COFFEA CRUDA',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (135,'2022-01-10','Carvedilol',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (643,'2022-02-08','Ensulizole, Octinoxate, and Titanium Dioxide',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (691,'2021-12-18','MENTHOL',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (958,'2021-11-01','WITCH HAZEL',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (781,'2021-04-05','Standardized Grass Pollen, Fescue, Meadow',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (805,'2021-05-23','White Ash',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (401,'2021-12-16','Rocky Mountain Juniper',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (197,'2021-06-20','Octinoxate and Oxybenzone',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (77,'2022-01-07','SENNA',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (130,'2021-09-26','Famotidine, Calcium Carbonate, Magnesium Hydroxide',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (161,'2021-11-11','Povidone-Iodine',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (197,'2022-02-02','Isosorbide mononitrate',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (431,'2021-04-01','Meloxicam',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (660,'2021-11-26','ETHYL ALCOHOL',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (15,'2021-03-09','Aurum Metallicum, Lithium Carbonicum, Serotonin',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (469,'2021-11-03','Pyrithione zinc',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (750,'2021-05-01','Privet',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (173,'2021-12-02','chloroxylenol',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (160,'2022-01-26','TRICLOSAN',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (985,'2021-10-07','Nitroglycerin',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (342,'2021-09-02','diltiazem hydrochloride',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (146,'2021-09-07','Olanzapine',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (393,'2021-05-20','Clarithromycin',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (865,'2021-05-23','lamotrigine',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (792,'2021-02-22','Amlodipine Besylate',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (141,'2021-12-27','ANASTROZOLE',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (550,'2021-11-14','doxycycline',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (304,'2022-01-11','Doxycycline Hyclate',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (811,'2021-10-14','WITCH HAZEL',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (258,'2021-04-13','Number Ten Mold Mixture',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (744,'2021-10-26','Aspirin',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (180,'2022-01-02','ETHYL ALCOHOL',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (172,'2021-05-16','OCTINOXATE, AMILOXATE, BEMOTRIZINOL, TITANIUM DIOXIDE',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (292,'2021-04-13','Oxymetazoline HCl',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (174,'2022-02-09','sodium phenylacetate and sodium benzoate',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (301,'2021-09-23','Equisetum Silicea',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (125,'2021-09-03','Oxygen',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (332,'2021-05-02','epinastine hydrochloride',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (488,'2021-05-31','Ranitidine',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (621,'2022-01-11','Fentanyl',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (194,'2022-01-08','Trazodone Hydrochloride',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (97,'2021-07-29','Polyethylene Glycol 3350',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (578,'2021-07-28','Ibuprofen',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (961,'2021-11-18','Octinoxate, Titanium Dioxide',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (154,'2021-10-05','Aluminum Zirconium Tetrachlorohydrex GLY',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (610,'2021-09-11','Mimulus',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (969,'2022-01-09','OCTINOXATE, TITANIUM DIOXIDE',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (781,'2022-02-04','Cantaloupe',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (123,'2021-08-09','Lansoprazole',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (860,'2021-09-19','doxepin hydrochloride',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (451,'2021-07-17','Anticaries',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (699,'2021-08-04','Aspirin',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (271,'2021-03-25','Allopurinol',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (616,'2021-08-14','Aranea diadema 12X, Conium maculatum 30X, Fumaria officinalis 6X, Galium aparine 12X, Hepar sulphuris calcareum 12X, Juglans regia 6X, Myosotis arvensis 6X, Sarsaparilla 6X, Scrophularia nodosa 6X',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (318,'2021-05-04','Triamcinolone Acetonide',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (126,'2021-10-14','Octinoxate and Oxybenzone',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (596,'2021-06-28','paroxetine hydrochloride',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (286,'2021-03-24','Influenzinum (combo), Histaminum hydrochloricum, Aconitum nap., Aralia quinquefolia, Arsenicum alb., Baptisia, Bryonia, Cinchona, Eupatorium perf., Gelsemium, Ipecac., Kali carb., Nux vom., Phosphorus, Rhus toxicodendron, Echinacea',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (566,'2021-09-11','Clarithromycin',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (19,'2021-10-13','laronidase',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (766,'2021-04-05','Goldenrod',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (959,'2021-04-26','ERYTHROMYCIN LACTOBIONATE',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (363,'2021-10-26','Nettle',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (691,'2022-02-13','Camphor, Menthol, and Methyl Salicylate',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (399,'2021-05-13','Carvedilol',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (888,'2021-10-06','Chlorpheniramine maleate and Phenylephrine HCl',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (490,'2021-12-27','OCTINOXATE, TITANIUM DIOXIDE, OCTISALATE, and OXYBENZONE',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (144,'2021-10-26','Argentum Metallicaum',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (982,'2021-11-28','Ziprasidone Hydrochloride',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (572,'2021-07-03','sulfacetamide sodium',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (965,'2022-02-02','BENZALKONIUM CHLORIDE AND PRAMOXINE HYDROCHLORIDE',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (141,'2021-04-14','Diphenoxylate Hydrochloride and Atropine Sulfate',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (449,'2022-01-11','Hydrochlorothiazide',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (820,'2021-11-04','OCTINOXATE, TITANIUM DIOXIDE, OXYBENZONE',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (859,'2022-01-09','Amitriptyline Hydrochloride',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (501,'2022-01-20','OCTINOXATE, OXYBENZONE',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (803,'2021-02-24','Hepar Magnesium 4',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (975,'2021-07-29','Paroxetine',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (461,'2021-12-09','LIDOCAINE HYDROCHLORIDE ANHYDROUS',true);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (821,'2021-03-31','glimepiride',false);
INSERT INTO pid_prescription(Pid,Issue_date,Content,Status) VALUES (376,'2021-12-22','Avobenzone, Octisalate, and Octocrylene',true);
